DisplayName "*Default machine data*"
ModelPath "/models/gxcustom1.dmd"
TopSpeed 996 1145
Acceleration 600 350
NormalGrip 0.995 0.9995
SkidGrip 0.25 0.25
Traction 2 2
BrakePower 0.95 0.65

EngineFireSpawner
    LocalPosition -0.72903 -3.1727 1.70776
;
EngineFireSpawner
    LocalPosition 0.72903 -3.1727 1.70776
;
EngineFireSpawner
    LocalPosition -0.72903 -3.1727 0.45223
;
EngineFireSpawner
    LocalPosition 0.72903 -3.1727 0.45223
;
